### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by pburkholder** [enriclluelles/redis-sentinel-proxy#3]
Hi - this is proving really useful, but we may need to make some customization. Since there's no license specified, the copyright is implicitly yours, and we can't customize/fork/reuse.

Could you please add an open-source license?  We'd recommend:

 https://creativecommons.org/share-your-work/public-domain/cc0/

But you may have your own preferences thoughts

Thanks! -Peter

**Comment by rogeruiz** [comment]
@enriclluelles any update on the possibility of adding an open-source licenses on this project?

**Comment by enriclluelles** [comment]
@pburkholder @rogeruiz Sorry, frankly I didn't realize this was being useful to someone else, and didn't see the issue. 
I added a license, the MIT license more specifically, hope that serves your purpose. Reopen the issue if it doesn't

**Comment by rogeruiz** [comment]
Thanks 🙏🏽 @enriclluelles. This makes our jobs a lot easier. We have some updates we needed to add to make this useful for our usecase around high-availability and resetting connections. I'll submit a PR later today.
